name: Call a reusable workflow

on:
  push:
    branches: [ "master" ]  
    
jobs:
  call-workflow-passing-data:
    uses: leesanaa2423/Awesome-TTRSS/.github/workflows/docker-image.yml@v1
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
